basePath: /api/v1/telemetry/
definitions:
  dto.CreateGPSInputDTO:
    properties:
      latitude:
        type: number
      longitude:
        type: number
      mac_address:
        type: string
    required:
    - latitude
    - longitude
    - mac_address
    type: object
  dto.CreateGyroscopeInputDTO:
    properties:
      mac_address:
        type: string
      model:
        type: string
      name:
        type: string
      x:
        type: number
      "y":
        type: number
      z:
        type: number
    required:
    - mac_address
    - model
    - name
    - x
    - "y"
    - z
    type: object
  dto.PhotoOutputDTO:
    properties:
      file_path:
        type: string
      id:
        type: string
      mac_address:
        type: string
      timestamp:
        type: string
    type: object
  web.Error:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a telemetry microservice API.
  title: telemetry Service API
  version: "1.0"
paths:
  /gps:
    post:
      consumes:
      - application/json
      description: "Create\tgps"
      parameters:
      - description: gps request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateGPSInputDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Error'
      summary: "Create\tgps"
      tags:
      - gps
  /gyroscope:
    post:
      consumes:
      - application/json
      description: "Create\tgyroscope"
      parameters:
      - description: gyroscope request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.CreateGyroscopeInputDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Error'
      summary: "Create\tgyroscope"
      tags:
      - gyroscopes
  /photo:
    post:
      consumes:
      - multipart/form-data
      description: Create photo
      parameters:
      - description: Photo file
        in: formData
        name: image
        required: true
        type: file
      - description: MAC Address
        in: formData
        name: mac_address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.PhotoOutputDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Error'
      summary: Create photo
      tags:
      - photos
swagger: "2.0"
